### ISSUE TITLE
Unhandled exception -assembly DigiRiteLogger...

### ISSUE THREAD

**Issue by K6TD** [w5xd/Digi-Rite#6] opened 2019-11-05 21:56 UTC
Version built from BETA branch.  Happens as soon as WL is started.

```************* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'DigiRiteLogger, Version=1.1.0.33, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'DigiRiteLogger, Version=1.1.0.33, Culture=neutral, PublicKeyToken=null'
   at DigiRite.MainForm.SetWlEntry(Object e)
   at DigiRite.Program.NoShowFormAppContext.<>c__DisplayClass8_0.<SetWlEntry>b__0(Object w)
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DigiRite
    Assembly Version: 1.1.0.33
    Win32 Version: 1.1.0.33
    CodeBase: file:///C:/Program%20Files%20(x86)/WriteLog/DigiRite/DigiRite.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
XDpack77Message
    Assembly Version: 1.0.0.16
    Win32 Version: 1.0.0.16
    CodeBase: file:///C:/Program%20Files%20(x86)/WriteLog/DigiRite/XDpack77Message.DLL
----------------------------------------```

**Comment by K6TD** [comment] 2019-11-05 22:00
One solution...copy the missing DLL from the build directory.

**Comment by w5xd** [comment] 2019-11-05 22:11
Hm... When I build the DigiRite solution, it has 3 projects (DigiRite, DigiRiteLogger, and Register) and all three .exe files end up bin/x86/Release.

So I don't know how it came to be that the DLL is missing because everything is in the build directory.

**Comment by K6TD** [comment] 2019-11-05 22:16
ls -laF of the release directory:
```kevin@Ham-stuff MINGW64 ~/source/repos/Digi-Rite2/bin/x86/Release (Beta)
$ ll
total 23209
-rwxr-xr-x 1 kevin 197121  175104 Nov  5 11:31 DigiRite.exe*
-rw-r--r-- 1 kevin 197121    4683 Nov  5 10:18 DigiRite.exe.config
-rw-r--r-- 1 kevin 197121  323072 Nov  5 11:31 DigiRite.pdb
-rwxr-xr-x 1 kevin 197121   14848 Nov  5 11:31 DigiRiteLogger.dll*
-rw-r--r-- 1 kevin 197121   24064 Nov  5 11:31 DigiRiteLogger.pdb
-rwxr-xr-x 1 kevin 197121 2391615 Jul 16 18:16 libfftw3f-3.dll*
-rwxr-xr-x 1 kevin 197121 1057630 Jul 16 18:16 libgcc_s_dw2-1.dll*
-rwxr-xr-x 1 kevin 197121 2406058 Jul 16 18:16 libgfortran-5.dll*
-rwxr-xr-x 1 kevin 197121  496043 Jul 16 18:16 libquadmath-0.dll*
-rw-r--r-- 1 kevin 197121  528833 Nov  5 10:18 ReadMe.htm
-rwxr-xr-x 1 kevin 197121   15872 Nov  5 11:31 Register.exe*
-rw-r--r-- 1 kevin 197121  536069 Nov  5 11:31 Register.iobj
-rw-r--r-- 1 kevin 197121   46800 Nov  5 11:31 Register.ipdb
-rw-r--r-- 1 kevin 197121 2134016 Nov  5 11:31 Register.pdb
-rwxr-xr-x 1 kevin 197121    5632 Oct  1 15:21 WriteLogIWaterfall.dll*
-rwxr-xr-x 1 kevin 197121  190464 Nov  5 11:26 XDAudioDevice.dll*
-rw-r--r-- 1 kevin 197121    4418 Oct  1 15:25 XDAudioDevice.dll.metagen
-rw-r--r-- 1 kevin 197121 3862528 Nov  5 11:26 XDAudioDevice.pdb
-rwxr-xr-x 1 kevin 197121  390656 Nov  5 11:26 XDft.dll*
-rw-r--r-- 1 kevin 197121    9454 Oct  1 15:25 XDft.dll.metagen
-rw-r--r-- 1 kevin 197121 4681728 Nov  5 11:26 XDft.pdb
-rwxr-xr-x 1 kevin 197121   41472 Nov  5 11:26 XDft8Test.exe*
-rw-r--r-- 1 kevin 197121     189 Oct  1 15:21 XDft8Test.exe.config
-rw-r--r-- 1 kevin 197121   65024 Nov  5 11:26 XDft8Test.pdb
-rwxr-xr-x 1 kevin 197121   19456 Nov  5 11:26 XDftDemod.exe*
-rw-r--r-- 1 kevin 197121  597087 Nov  5 11:26 XDftDemod.iobj
-rw-r--r-- 1 kevin 197121   64320 Nov  5 11:26 XDftDemod.ipdb
-rw-r--r-- 1 kevin 197121 2265088 Nov  5 11:26 XDftDemod.pdb
-rwxr-xr-x 1 kevin 197121   98816 Nov  5 11:26 XDftRxAudioProcess.dll*
-rw-r--r-- 1 kevin 197121     854 Oct  1 15:25 XDftRxAudioProcess.dll.metagen
-rw-r--r-- 1 kevin 197121  716800 Nov  5 11:26 XDftRxAudioProcess.pdb
-rwxr-xr-x 1 kevin 197121   14848 Nov  5 11:26 XDpack77Message.dll*
-rw-r--r-- 1 kevin 197121   46592 Nov  5 11:26 XDpack77Message.pdb
-rwxr-xr-x 1 kevin 197121  477658 Jul 16 18:16 XDwsjtFT.dll*
```


I copied over the Register.exe, the DigiRite.exe and the DIgiRiteLogger.dll.

**Comment by w5xd** [comment] 2019-11-05 22:22
Where did you find Register.exe and DigiRiteLogger.dll? I need to figure out how they got where they are instead of in the bin/x86/Release.

When I fetch the Beta branch and build it, ALL the binaries end up in the directory you listed above. That is, I don't see the problem. And the script (for users fetching the master branch, but the Beta branch should be no different) says this:

> The entire build directory, bin\x86\Release, is required to run DigiRite, but the (typically huge) .pdb files are not needed and may be deleted.

The Beta branch solution differs from the master branch solution in that those two missing binaries don't even exist in the older branch.

**Comment by w5xd** [comment] 2019-11-05 23:43
Guessing that maybe the problem is that the build-from-source instructions on writelog.com are unclear, I changed them just now: https://writelog.com/digirite-build
The "run on another machine" instructions say how the result of the build is intended to be "installed". (Copy the contents of /bin/x86/Release, excepting the pdb files, and then run Register.exe)

Does that explain this issue?

**Comment by k6mr** [comment] 2019-11-06 00:49
V. 1.1.32 built fine.

Wayne: I received your invitation from GitHub but when I try to go to the link it says: Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

I’m already subscribed and getting your messages. If there is something else I need to do let me know.

Thanks for all your time with this project.

Ken K6MR

________________________________

**Comment by K6TD** [comment] 2019-11-06 00:52
Hi Ken,

The build issues are on the BETA branch.

KR

**Comment by w5xd** [comment] 2019-11-06 12:57
Fixed by updating the how-to-install paragraph for users at http:/writelog.com/digirite-build

**Closed as completed** 2019-11-06 12:57 UTC
